Algoritmo "medidas"

Var

   A, B, C, quadrado, triangulo, trapezio: real

Inicio

   escreva("Digite a medida A: ")
   leia(A)
   escreva("Digite a medida B: ")
   leia(B)
   escreva("Digite a medida C: ")
   leia(C)
   
   quadrado <- exp(A, 2)

   escreval("AREA DO QUADRADO = ", quadrado:8:4)
   
   triangulo <- A * B / 2
   
   escreval("AREA DO TRIANGULO = ", triangulo:8:4)
   
   trapezio <-  (A + B) * C / 2
   
   escreva("AREA DO TRAPEZIO = ", trapezio:8:4)
   
   


Fimalgoritmo